# Generated by Django 5.1.1 on 2024-10-21 21:35

import django.db.models.deletion
from django.db import migrations, models

def crear_datos(apps, schema_editor):
    Empleado = apps.get_model('mibibluna_app', 'Empleado')
    Editorial = apps.get_model('mibibluna_app', 'Editorial')
    Autor = apps.get_model('mibibluna_app', 'Autor')
    Libro = apps.get_model('mibibluna_app', 'Libro')

    # Crear empleados
    empleados = [
        {'nombre': 'Juan', 'apellido': 'Pérez', 'legajo': 1},
        {'nombre': 'Ana', 'apellido': 'Gómez', 'legajo': 2},
        {'nombre': 'Luis', 'apellido': 'Fernández', 'legajo': 3},
    ]
    for emp in empleados:
        Empleado.objects.get_or_create(**emp)

    # Crear editoriales
    editoriales = [
        {'nombre': 'Editorial Planeta', 'telefono': '011-1234-5678', 'email': 'contacto@planetabooks.com'},
        {'nombre': 'Ediciones SM', 'telefono': '011-2345-6789', 'email': 'info@ediciones-sm.com'},
        {'nombre': 'Penguin Random House', 'telefono': '011-3456-7890', 'email': 'info@penguinrandomhouse.com'},
    ]
    for ed in editoriales:
        Editorial.objects.get_or_create(**ed)

    # Crear autores
    autores_nombres = [
        ('Ernesto', 'Sabato'),
        ('John', 'Boyne'),
        ('Horacio', 'Quiroga'),
        ('Pablo', 'De Santis'),
        ('Antonio', 'Garrido'),
        ('Alberto', 'Manguel'),
        ('Frances', 'Hodgson Burnett'),
        ('Isabel', 'Allende'),
        ('C.S.', 'Lewis'),
        ('Markus', 'Zusak'),
    ]

    autores = []
    for nombre, apellido in autores_nombres:
        autor, _ = Autor.objects.get_or_create(nombre=nombre, apellido=apellido)
        autores.append(autor)

    # Crear libros
    libros = [
        {'titulo': 'El túnel', 'ISBN': '978-3-16-148410-0', 'ano_publicacion': 1948, 'autor': autores[0]},
        {'titulo': 'El niño con el pijama de rayas', 'ISBN': '978-0-09-957108-1', 'ano_publicacion': 2006, 'autor': autores[1]},
        {'titulo': 'Cuentos de la selva', 'ISBN': '978-950-04-2311-1', 'ano_publicacion': 1918, 'autor': autores[2]},
        {'titulo': 'Mariposa', 'ISBN': '978-950-08-0507-2', 'ano_publicacion': 2003, 'autor': autores[3]},
        {'titulo': 'Los ojos del perro siberiano', 'ISBN': '978-950-07-1334-4', 'ano_publicacion': 1992, 'autor': autores[4]},
        {'titulo': 'Mundo del fin del mundo', 'ISBN': '978-950-03-0155-3', 'ano_publicacion': 1992, 'autor': autores[5]},
        {'titulo': 'El jardín secreto', 'ISBN': '978-0-06-440188-3', 'ano_publicacion': 1911, 'autor': autores[6]},
        {'titulo': 'La casa de los espíritus', 'ISBN': '978-84-204-2920-1', 'ano_publicacion': 1982, 'autor': autores[7]},
        {'titulo': 'Las crónicas de Narnia', 'ISBN': '978-0-06-440499-0', 'ano_publicacion': 1950, 'autor': autores[8]},
        {'titulo': 'La ladrona de libros', 'ISBN': '978-0-19-272500-4', 'ano_publicacion': 2005, 'autor': autores[9]},
        {'titulo': 'Cien años de soledad', 'ISBN': '978-84-376-0494-7', 'ano_publicacion': 1967, 'autor': autores[0]},
        {'titulo': 'Rayuela', 'ISBN': '978-950-04-0540-0', 'ano_publicacion': 1963, 'autor': autores[0]},
        {'titulo': 'Ficciones', 'ISBN': '978-950-07-1113-5', 'ano_publicacion': 1944, 'autor': autores[0]},
        {'titulo': 'El aleph', 'ISBN': '978-950-07-1124-1', 'ano_publicacion': 1949, 'autor': autores[0]},
        {'titulo': 'Sobre héroes y tumbas', 'ISBN': '978-950-04-0323-9', 'ano_publicacion': 1961, 'autor': autores[0]},
        {'titulo': 'La invención de Morel', 'ISBN': '978-950-08-0072-5', 'ano_publicacion': 1940, 'autor': autores[0]},
        {'titulo': 'El túnel del tiempo', 'ISBN': '978-84-667-1374-4', 'ano_publicacion': 2001, 'autor': autores[0]},
        {'titulo': 'Crónicas de la calle 32', 'ISBN': '978-950-04-2177-5', 'ano_publicacion': 2004, 'autor': autores[0]},
        {'titulo': 'Don Segundo Sombra', 'ISBN': '978-950-04-0319-2', 'ano_publicacion': 1926, 'autor': autores[0]},
        {'titulo': 'Martín Fierro', 'ISBN': '978-950-03-2170-8', 'ano_publicacion': 1872, 'autor': autores[0]},
        {'titulo': 'Los siete locos', 'ISBN': '978-950-04-2161-4', 'ano_publicacion': 1929, 'autor': autores[0]},
        {'titulo': 'El matadero', 'ISBN': '978-950-07-0361-8', 'ano_publicacion': 1871, 'autor': autores[0]},
        {'titulo': 'El Eternauta', 'ISBN': '978-987-1390-14-0', 'ano_publicacion': 1957, 'autor': autores[0]},
        {'titulo': 'El llanto', 'ISBN': '978-950-07-1116-6', 'ano_publicacion': 2003, 'autor': autores[0]},
        {'titulo': 'La casa de Adela', 'ISBN': '978-987-1985-50-5', 'ano_publicacion': 2004, 'autor': autores[0]},
        {'titulo': 'El mundo de Sofía', 'ISBN': '978-950-04-1238-2', 'ano_publicacion': 1991, 'autor': autores[0]},
        {'titulo': 'El guardián entre el centeno', 'ISBN': '978-0-316-76948-0', 'ano_publicacion': 1951, 'autor': autores[0]},
        {'titulo': 'Las ventajas de ser un marginado', 'ISBN': '978-0-316-13148-3', 'ano_publicacion': 2012, 'autor': autores[0]},
        {'titulo': 'El señor de los anillos', 'ISBN': '978-0-345-33968-3', 'ano_publicacion': 1954, 'autor': autores[0]},
        {'titulo': 'Harry Potter y la piedra filosofal', 'ISBN': '978-0-7475-3274-5', 'ano_publicacion': 1997, 'autor': autores[0]},
        {'titulo': 'La serie de los juegos del hambre', 'ISBN': '978-0-439-02348-1', 'ano_publicacion': 2008, 'autor': autores[0]},
        {'titulo': 'Divergente', 'ISBN': '978-0-06-228850-2', 'ano_publicacion': 2011, 'autor': autores[0]},
        {'titulo': 'Fahrenheit 451', 'ISBN': '978-0-7432-4769-3', 'ano_publicacion': 1953, 'autor': autores[0]},
        {'titulo': 'El Corazón de la Tierra', 'ISBN': '978-987-1171-49-4', 'ano_publicacion': 2012, 'autor': autores[0]},
        {'titulo': 'La máquina del tiempo', 'ISBN': '978-0-14-028209-8', 'ano_publicacion': 1895, 'autor': autores[0]},
        {'titulo': 'La historia interminable', 'ISBN': '978-84-204-0315-2', 'ano_publicacion': 1979, 'autor': autores[0]},
        {'titulo': 'El hobbit', 'ISBN': '978-0-618-00221-3', 'ano_publicacion': 1937, 'autor': autores[0]},
        {'titulo': 'Cazadores de sombras', 'ISBN': '978-0-684-85733-4', 'ano_publicacion': 2007, 'autor': autores[0]},
        {'titulo': 'La sombra del viento', 'ISBN': '978-84-204-5381-1', 'ano_publicacion': 2001, 'autor': autores[0]},
        {'titulo': 'Cazadores de sombras', 'ISBN': '978-0-684-85732-7', 'ano_publicacion': 2007, 'autor': autores[0]},
        {'titulo': 'El príncipe de la niebla', 'ISBN': '978-84-204-7281-6', 'ano_publicacion': 1993, 'autor': autores[0]},
        {'titulo': 'El camino', 'ISBN': '978-84-8160-255-6', 'ano_publicacion': 1992, 'autor': autores[0]},
        {'titulo': 'La tregua', 'ISBN': '978-987-215-053-7', 'ano_publicacion': 1960, 'autor': autores[0]},
        {'titulo': 'El túnel de la vida', 'ISBN': '978-987-325-213-1', 'ano_publicacion': 2005, 'autor': autores[0]},
        {'titulo': 'La ciudad de las bestias', 'ISBN': '978-84-204-0277-8', 'ano_publicacion': 2002, 'autor': autores[0]},
        {'titulo': 'El viaje de las estrellas', 'ISBN': '978-987-1045-37-1', 'ano_publicacion': 1998, 'autor': autores[0]},
        {'titulo': 'Agujeros negros y agujeros de gusano', 'ISBN': '978-950-07-1191-3', 'ano_publicacion': 2007, 'autor': autores[0]},
        {'titulo': 'El ciclo de la luna roja', 'ISBN': '978-950-07-1936-9', 'ano_publicacion': 2005, 'autor': autores[0]},
        {'titulo': 'Un monstruo viene a verme', 'ISBN': '978-84-666-4176-3', 'ano_publicacion': 2011, 'autor': autores[0]},
    ]

    for libro in libros:
        Libro.objects.create(
            titulo=libro['titulo'],
            ISBN=libro['ISBN'],
            ano_publicacion=libro['ano_publicacion'],
            autor=libro['autor'],
            activo=True,
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=38)),
                ('apellido', models.CharField(max_length=38)),
                ('nacionalidad', models.CharField(max_length=38, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=38)),
                ('telefono', models.CharField(default=None, max_length=38, null=True)),
                ('email', models.EmailField(default=None, max_length=38, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=38)),
                ('apellido', models.CharField(max_length=38)),
                ('legajo', models.IntegerField(verbose_name='Legajo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=38)),
                ('apellido', models.CharField(max_length=38)),
                ('direccion', models.CharField(max_length=38, null=True)),
                ('telefono', models.CharField(max_length=38, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=38)),
                ('ISBN', models.CharField(max_length=30)),
                ('ano_publicacion', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores_libros', to='mibibluna_app.autor', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_realizados', to='mibibluna_app.empleado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='mibibluna_app.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='mibibluna_app.socio')),
            ],
        ),
        migrations.RunPython(crear_datos),
    ]
