# Generated by Django 5.1.1 on 2024-10-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibibluna_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name_plural': 'Editoriales'},
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='ISBN',
            new_name='isbn',
        ),
        migrations.AlterField(
            model_name='libro',
            name='ano_publicacion',
            field=models.IntegerField(null=True, verbose_name='Año de Publicación'),
        ),
    ]
