# Generated by Django 5.1.1 on 2024-10-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibibluna_app', '0002_alter_autor_options_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
